name: Release GHPR Packages

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  package-binary:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - name: Checkout Repository to Runner Context
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Setup Node
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"
          cache: "yarn"
          scope: "@stormsinbrewing"
      - name: Publish Binary to GitHub Packages
        run: |
          yarn install
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
