name: Release GHPR Packages

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  package-binary:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Checkout Repository to Runner Context
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"
          cache: "yarn"
          scope: "@stormsinbrewing"
      - name: Publish Binary to GitHub Packages
        run: |
          yarn install
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
