name: Release GHPR Packages

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  package-binary:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - name: Checkout Repository to Runner Context
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"
          cache: "yarn"
          scope: "@stormsinbrewing"
      - name: Publish Binary to GitHub Packages
        run: |
          yarn install
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
